<?PHP
// ----------------------------------------------------------------------------
// Tabelle mit den XML-Tag-Namen der Effects im Client und in der EMU
// ----------------------------------------------------------------------------
$tabefftags = array(
              // Client-Tag                          EMU-Tag
                "absoluteslow"                   => "absoluteslow",
                "absolutesnare"                  => "absolutesnare",
                "absolutestattopcbuff"           => "absstatbuff",
                "absolutestattopcdebuff"         => "absstatdebuff",
                "alwaysblock"                    => "alwaysblock",
                "alwaysdodge"                    => "alwaysdodge",
                "alwaysparry"                    => "alwaysparry",
                "alwaysresist"                   => "alwaysresist",
                "apboost"                        => "apboost",
                "amr_mastery"                    => "armormastery",
                "aura"                           => "aura",
                "backdashatk"                    => "backdash",
                "bind"                           => "bind",
                "bleed"                          => "bleed",
                "blind"                          => "blind",
                "boostdroprate"                  => "boostdroprate",
                "boosthate"                      => "boosthate",
                "boosthealeffect"                => "boostheal",
                "boostskillcastingtime"          => "boostskillcastingtime",
                "boostskillcost"                 => "boostskillcost",
                "boostspellattackeffect"         => "boostspellattack",
                "buffbind"                       => "buffbind",
                "buffsilence"                    => "buffsilence",
                "buffsleep"                      => "buffsleep",
                "buffstun"                       => "buffstun",
                "carvesignet"                    => "carvesignet",
                "caseheal"                       => "caseheal",
                "changehateonattacked"           => "changehateonattacked",
                "closeaerial"                    => "closeaerial",
                "condskilllauncher"              => "condskilllauncher",
                "confuse"                        => "confuse",
                "convertheal"                    => "convertheal",
                "curse"                          => "curse",
                "dashatk"                        => "dash",
                "deathblow"                      => "deathblow",
                "deboostheal"                    => "deboostheal",
                "deform"                         => "deform",
                "delaydamage"                    => "delaydamage",
                "delayedfpatk_instant"           => "delayedfpatk_instant",
                "delayedskill"                   => "delayedskill",
                "disease"                        => "disease",
                "dispel"                         => "dispel",
                "dispelbuff"                     => "dispelbuff",
                "dispelbuffcounteratk"           => "dispelbuffcounteratk",
                "dispeldebuff"                   => "dispeldebuff",
                "dispeldebuffmental"             => "dispeldebuffmental",
                "dispeldebuffphysical"           => "dispeldebuffphysical",
                "dispelnpcbuff"                  => "dispelnpcbuff",
                "dispelnpcdebuff"                => "dispelnpcdebuff",
                "dpheal"                         => "dpheal",
                "dphealinstant"                  => "dphealinstant",
                "dptransfer"                     => "dptransfer",
                "drboost"                        => "drboost",
                "escape"                         => "escape",
                "evade"                          => "evade",
                "extendedaurarange"              => "extendedaurarange",
                "fall"                           => "fall",
                "fear"                           => "fear",
                "flyoff"                         => "flyoff",
                "fpatk"                          => "fpatk",
                "fpatkinstant"                   => "fpatkinstant",
                "fpheal"                         => "fpheal",
                "fphealinstant"                  => "fphealinstant",
                "heal"                           => "heal",
                "healcastoronatk"                => "healcastoronatk",
                "healcastorontargetdead"         => "healcastorontargetdead",
                "healinstant"                    => "healinstant",
                "hide"                           => "hide",
                "hipass"                         => "hipass",
                "hostileup"                      => "hostileup",
                "invulnerablewing"               => "invulnerablewing",
                "magiccounteratk"                => "magiccounteratk",
                "movebehind"                     => "movebehind",
                "mpattack"                       => "mpattack",
                "mpattackinstant"                => "mpattackinstant",
                "mpheal"                         => "mpheal",
                "mphealinstant"                  => "mphealinstant",
                "mpshield"                       => "mpshield",
                "nodeathpenalty"                 => "nodeathpenalty",
                "nofly"                          => "nofly",
                "nofpconsum"                     => "nofpconsum",
                "noreducespellatk"               => "noreducespellatk",
                "noresurrectpenalty"             => "noresurrectpenalty",
                "onetimeboostheal"               => "onetimeboostheal",
                "onetimeboostskillattack"        => "onetimeboostskillattack",
                "onetimeboostskillcritical"      => "onetimeboostskillcritical",
                "openaerial"                     => "openaerial",
                "paralyze"                       => "paralyze",
                "petorderuseultraskill"          => "petorderuseultraskill",
                "poison"                         => "poison",
                "polymorph"                      => "polymorph",
                "procatk_instant"                => "procatk_instant",
                "procdphealinstant"              => "procdphealinstant",
                "procfphealinstant"              => "procfphealinstant",
                "prochealinstant"                => "prochealinstant",
                "procmphealinstant"              => "procmphealinstant",
                "procvphealinstant"              => "procvphealinstant",
                "protect"                        => "protect",
                "provoker"                       => "provoker",
                "pulled"                         => "pulled",
                "randommoveloc"                  => "randommoveloc",
                "rebirth"                        => "rebirth",
                "recallinstant"                  => "recallinstant",
                "reflector"                      => "reflector",
                "resurrect"                      => "resurrect",
                "resurrectbase"                  => "resurrectbase",
                "resurrectpos"                   => "resurrectpos",
                "returnhome"                     => "return",
                "returnpoint"                    => "returnpoint",
                "riderobot"                      => "riderobot",
                "sanctuary"                      => "sanctuary",
                "search"                         => "search",
                "shapechange"                    => "shapechange",
                "shield"                         => "shield",
                "shieldmastery"                  => "shieldmastery",
                "signet"                         => "signet",
                "signetburst"                    => "signetburst",
                "silence"                        => "silence",
                "simpleroot"                     => "simpleroot",
                "skillatk"                       => "skillatk",
                "skillatkdraininstant"           => "skillatkdraininstant",
                "skillcooltimereset"             => "skillcooltimereset",
                "skilllauncher"                  => "skilllauncher",
                "skillxpboost"                   => "skillxpboost",
                "sleep"                          => "sleep",
                "slow"                           => "slow",
                "snare"                          => "snare",
                "spellatk"                       => "spellatk",
                "spellatkdrain"                  => "spellatkdrain",
                "spellatkdraininstant"           => "spellatkdraininstant",
                "spellatkinstant"                => "spellatkinstant",
                "spin"                           => "spin",
                "stagger"                        => "stagger",
                "statboost"                      => "statboost",
                "statdown"                       => "statdown",
                "statup"                         => "statup",
                "stumble"                        => "stumble",
                "stun"                           => "stun",
                "subtypeboostresist"             => "subtypeboostresist",
                "subtypeextendduration"          => "subtypeextendduration",
                "summon"                         => "summon",
                "summonbindinggroupgate"         => "summonbindinggroupgate",
                "summonfunctionalnpc"            => "summonfunctionalnpc",
                "summongroupgate"                => "summongroupgate",
                "summonhoming"                   => "summonhoming",
                "summonhousegate"                => "summonhousegate",
                "summonservant"                  => "summonservant",
                "summonskillarea"                => "summonskillarea",
                "summontotem"                    => "summontotem",
                "summontrap"                     => "summontrap",
                "switchhostile"                  => "switchhostile",
                "switchhpmp"                     => "switchhpmp",
                "targetchange"                   => "targetchange",
                "targetteleport"                 => "targetteleport",
                "weaponstatboost"                => "weaponstatboost",
                "weaponstatup"                   => "weaponstatup",
                "wpndual"                        => "wpndual",
                "wpn_mastery"                    => "wpnmastery",
                "xpboost"                        => "xpboost",
                "stunalways"                     => "stunalways"
              );
                
// ----------------------------------------------------------------------------
// Effect-Tag aus Client für EMU zurückgeben
// ----------------------------------------------------------------------------
function getEmuEffectTag($cname)
{
    global $tabefftags;
    
    $key = strtolower($cname);
    
    if (isset($tabefftags[$key]))
        return $tabefftags[$key];
    else
        return $key;
}